-- Riyadh Glass AI + CRM additive migration
-- Safe to re-run. Designed for the existing bigint leads/messages/media schema.

alter table public.leads add column if not exists email text;
alter table public.leads add column if not exists source_context jsonb not null default '{}'::jsonb;
alter table public.leads add column if not exists notes text;
alter table public.leads add column if not exists status text not null default 'new';
alter table public.leads add column if not exists score integer not null default 0;
alter table public.leads add column if not exists temperature text not null default 'cold';
alter table public.leads add column if not exists calc_area numeric;
alter table public.leads add column if not exists calc_type text;
alter table public.leads add column if not exists calc_price numeric;
alter table public.leads add column if not exists assigned_admin uuid;
alter table public.leads add column if not exists follow_up_at timestamptz;
alter table public.leads add column if not exists last_activity_at timestamptz not null default now();
alter table public.leads add column if not exists updated_at timestamptz not null default now();

do $$ begin alter table public.leads add constraint leads_status_check check (status in ('new','contacted','interested','quote_sent','won','lost','closed')); exception when duplicate_object then null; end $$;
do $$ begin alter table public.leads add constraint leads_temperature_check check (temperature in ('hot','warm','cold')); exception when duplicate_object then null; end $$;
do $$ begin alter table public.leads add constraint leads_score_check check (score between 0 and 100); exception when duplicate_object then null; end $$;

create index if not exists leads_created_at_idx on public.leads(created_at desc);
create index if not exists leads_status_idx on public.leads(status);
create index if not exists leads_source_idx on public.leads(source);
create index if not exists leads_score_idx on public.leads(score desc);

create table if not exists public.lead_activities (
  id bigint generated by default as identity primary key,
  lead_id bigint not null references public.leads(id) on delete cascade,
  activity_type text not null,
  details jsonb not null default '{}'::jsonb,
  created_by uuid,
  created_at timestamptz not null default now()
);
create index if not exists lead_activities_lead_created_idx on public.lead_activities(lead_id, created_at desc);

create table if not exists public.admin_activity (
  id bigint generated by default as identity primary key,
  admin_user_id uuid,
  action text not null,
  entity_type text,
  entity_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists admin_activity_created_idx on public.admin_activity(created_at desc);

alter table public.messages add column if not exists email text;
alter table public.messages add column if not exists status text not null default 'new';
alter table public.messages add column if not exists archived_at timestamptz;

alter table public.media add column if not exists type text;
alter table public.media add column if not exists size bigint;

create or replace function public.set_updated_at() returns trigger language plpgsql set search_path = public as $$ begin new.updated_at = now(); return new; end; $$;
drop trigger if exists set_leads_updated_at on public.leads;
create trigger set_leads_updated_at before update on public.leads for each row execute function public.set_updated_at();

alter table public.leads enable row level security;
alter table public.lead_activities enable row level security;
alter table public.admin_activity enable row level security;

drop policy if exists "public can create leads" on public.leads;
create policy "public can create leads" on public.leads for insert to anon, authenticated with check (coalesce(length(trim(phone)),0) > 0 or coalesce(length(trim(email)),0) > 0);
drop policy if exists "admins can manage leads" on public.leads;
create policy "admins can manage leads" on public.leads for all to authenticated using (exists (select 1 from public.admins a where a.user_id = auth.uid())) with check (exists (select 1 from public.admins a where a.user_id = auth.uid()));
drop policy if exists "admins can manage lead activities" on public.lead_activities;
create policy "admins can manage lead activities" on public.lead_activities for all to authenticated using (exists (select 1 from public.admins a where a.user_id = auth.uid())) with check (exists (select 1 from public.admins a where a.user_id = auth.uid()));
drop policy if exists "admins can manage admin activity" on public.admin_activity;
create policy "admins can manage admin activity" on public.admin_activity for all to authenticated using (exists (select 1 from public.admins a where a.user_id = auth.uid())) with check (exists (select 1 from public.admins a where a.user_id = auth.uid()));
